Tt 4864 better error handling
sealink/ci-deploy pull request #10
Opened 2018-11-20 04:22 UTC by jmortlock

### WHY
Allows reporting success / failed builds to rollbar

2018-11-20 04:50 UTC, HellRok requested changes

2018-11-20 04:50 UTC, HellRok commented on bin/deploy
> +function update_deployment {
The indenting on this function is wrong

2018-11-20 04:50 UTC, HellRok commented on bin/deploy
> +function create_deployment {
this function has incorrect indenting too

2018-11-20 08:27 UTC, jmortlock commented on bin/deploy
> +function update_deployment {
Sorted

2018-11-21 00:20 UTC, Steffylicious approved these changes

2018-11-21 00:20 UTC, HellRok approved these changes

2018-11-21 00:21 UTC, merged